name: miecal
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  qr_flutter: ^4.0.0

  table_calendar: ^3.2.0

  cupertino_icons: ^1.0.8
  go_router: ^15.2.4

  firebase_core: ^2.30.1
  firebase_auth: ^4.17.4
  cloud_firestore: ^4.15.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  assets:
    - assets/sample_image1.png
    - assets/sample_image2.png
    - assets/sample_image3.png
    - assets/sample_image4.png
    - assets/sample_image5.png
    - assets/sample_image6.png
    - assets/onset_date.png
    - assets/QR.png
  uses-material-design: true
