name: miecal
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  qr_flutter: ^4.0.0
  image: ^4.1.3
  table_calendar: ^3.1.3
  cupertino_icons: ^1.0.8
  go_router: ^15.1.3
  firebase_core: ^2.30.1
  firebase_auth: ^4.17.4
  google_sign_in: ^6.2.1
  cloud_firestore: ^4.15.5
  provider: ^6.1.5
  vibration: ^2.0.2
  audioplayers: ^5.2.1
  google_fonts: ^6.2.1
  numberpicker: ^2.1.2
  mobile_scanner: ^7.0.1
  intl: ^0.20.0
  font_awesome_flutter: ^10.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  assets:
    - assets/sample_image1.png
    - assets/sample_image2.png
    - assets/sample_image3.png
    - assets/sample_image4.png
    - assets/sample_image5.png
    - assets/sample_image6.png
    - assets/sample_image7.png
    - assets/sample_image8.png
    - assets/onset_date.png
    - assets/show_screen.png
    - assets/images/
    - assets/
    - assets/icons/
    - assets/human_outline.png
    - assets/body_mask.png
    - assets/ios_light_google.png
    - assets/google_light_new.png
    - assets/man_image.png
    - assets/woman_image.png
  #uses-material-design: true
  #generate: true
