name: miecal
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  qr_flutter: ^4.1.0
  image: ^4.1.3
  table_calendar: ^3.1.3
  cupertino_icons: ^1.0.8
  go_router: ^16.0.0
  firebase_core: ^2.32.0
  firebase_auth: ^4.20.0
  google_sign_in: ^6.3.0
  cloud_firestore: ^4.17.5
  provider: ^6.1.5
  vibration: ^2.1.0
  audioplayers: ^6.5.0
  google_fonts: ^6.2.1
  numberpicker: ^2.1.2
  mobile_scanner: ^7.0.1
  intl: ^0.19.0
  app_links: ^6.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  assets:
    - assets/
    - assets/images/
    - assets/images/affected_area/
    - assets/images/cause/
    - assets/images/login/
    - assets/images/menu/
    - assets/images/other_information/
    - assets/images/suffer_level/
    - assets/images/symptom/
    - assets/images/top/
    - assets/show_screen.png
    - assets/man_image.png
    - assets/woman_image.png
    - assets/monnsinnhyo.png
  uses-material-design: true
  generate: true
